/*
 * ======================================================================================
 * PROJECT: GRAVE RTC Controller with MP3
 * VERSION: 6.9-final
 * HARDWARE: M5Atom S3 Lite + Base AtomPortABC + RTC Unit + Relay Unit + AudioPlayer Unit
 * AUTHOR: Generated by AI Assistant guided by Mauricio Martins.
 * DATE: March 05, 2026
 *
 * CHANGELOG :
 * - [FIX 20] CRITICAL: N9301 Audio Chip volume limit is strictly 0-30. The previous
 *            assumption of native 0-255 range was incorrect. Sending 255 (0xFF) 
 *            muted/crashed the DAC. Test code worked because 50 is gracefully 
 *            ignored by the chip. Fixed all constraints and HTML to 0-30.
 * -[FIX 21] Incremented EEPROM signature to 0xBBCCDD04 to wipe the corrupted 255 
 *            volume value and safely default to 15 (medium volume).
 * - Restored Relay logic to M5Stack standard (HIGH = ON, LOW = OFF).
 * ======================================================================================
 */

#include <M5AtomS3.h>
#include <WiFi.h>
#include <WebServer.h>
#include <EEPROM.h>
#include <unit_audioplayer.hpp>

// ===================================================================================
// PINOUT & LOGIC
// ===================================================================================
const int OUTPUT_PIN = 7;
#define MP3_RX_PIN    6
#define MP3_TX_PIN    5

const int RELAY_ON  = HIGH;
const int RELAY_OFF = LOW;

// ===================================================================================
// ACCESS POINT
// ===================================================================================
const char*     ap_ssid     = "GRAVE";
const char*     ap_password = "grave123";
const IPAddress AP_IP(192, 168, 4, 1);
const IPAddress AP_GATEWAY(192, 168, 4, 1);
const IPAddress AP_SUBNET(255, 255, 255, 0);

// ===================================================================================
// EEPROM / CONFIG
// ===================================================================================
#define EEPROM_SIZE      512
const int CONFIG_ADDRESS = 0;
#define MAX_PERIODS      3
#define EEPROM_SIGNATURE 0xBBCCDD04 // Incremented to force volume reset

struct Period {
    int start_h = 0, start_m = 0;
    int end_h   = 0, end_m   = 0;
};

struct AlarmData {
    int      num_periods         = 0;
    Period   periods[MAX_PERIODS];
    int      volume              = 15; // MAX is 30 for N9301 Audio chip!
    uint32_t signature           = EEPROM_SIGNATURE;
};

// ===================================================================================
// SHARED STATE (Core 0 <-> Core 1) — protected by configMux
// ===================================================================================
portMUX_TYPE  configMux = portMUX_INITIALIZER_UNLOCKED;

AlarmData     alarmConfig;
volatile bool is_alarm_active = false;
volatile bool manual_play     = false;

volatile int  sharedHours   = 0;
volatile int  sharedMinutes = 0;
volatile int  sharedSeconds = 0;
volatile int  sharedDay     = 0;
volatile int  sharedMonth   = 0;
volatile int  sharedYear    = 0;

volatile bool    pendingVolumeFlag  = false;
volatile uint8_t pendingVolumeValue = 0;

volatile bool pendingTimeFlag = false;
struct PendingTime { int h, m, s, d, mon, y; };
PendingTime pendingTime;  

// ===================================================================================
// GLOBALS (Core 1 only)
// ===================================================================================
AudioPlayerUnit  mp3;
bool             mp3_ok         = false;
unsigned long    previousMillis = 0;
const long       alarmInterval  = 1000;

// ===================================================================================
// GLOBALS (Core 0 only)
// ===================================================================================
WebServer     server(80);
TaskHandle_t  webTaskHandle;

// ===================================================================================
// LED (Core 1 only)
// ===================================================================================
void showLED(uint32_t color) {
    AtomS3.dis.drawpix(color);
    AtomS3.dis.show();
}

// ===================================================================================
// EEPROM
// ===================================================================================
void saveAlarmConfig() {
    EEPROM.put(CONFIG_ADDRESS, alarmConfig);
    EEPROM.commit();
}

void loadAlarmConfig() {
    EEPROM.get(CONFIG_ADDRESS, alarmConfig);
    if (alarmConfig.signature != EEPROM_SIGNATURE) {
        Serial.println("[EEPROM] Invalid/outdated data. Resetting to defaults.");
        AlarmData defaults;
        alarmConfig = defaults;
        saveAlarmConfig();
    }
    alarmConfig.volume = constrain(alarmConfig.volume, 0, 30); // Absolute max is 30!
}

// ===================================================================================
// ALARM STATE MACHINE (Core 1 only)
// ===================================================================================
void checkAlarmState() {
    int now_min = sharedHours * 60 + sharedMinutes;

    portENTER_CRITICAL(&configMux);
    AlarmData cfg    = alarmConfig;
    bool      manual = manual_play;
    portEXIT_CRITICAL(&configMux);

    bool rtc_active = false;
    for (int i = 0; i < cfg.num_periods; i++) {
        Period p      = cfg.periods[i];
        int start_min = p.start_h * 60 + p.start_m;
        int end_min   = p.end_h   * 60 + p.end_m;
        if (start_min == end_min) continue; 
        bool hit = (start_min < end_min)
                   ? (now_min >= start_min && now_min < end_min)
                   : (now_min >= start_min || now_min < end_min); 
        if (hit) { rtc_active = true; break; }
    }

    bool should_active = rtc_active || manual;

    if (should_active && !is_alarm_active) {
        digitalWrite(OUTPUT_PIN, RELAY_ON);
        
        portENTER_CRITICAL(&configMux);
        is_alarm_active = true;
        portEXIT_CRITICAL(&configMux);
        
        Serial.printf("[ALARM] ACTIVATED: %02d:%02d\n", sharedHours, sharedMinutes);
        
        if (mp3_ok) {
            mp3.setVolume(cfg.volume);
            delay(50);
            mp3.setPlayMode(AUDIO_PLAYER_MODE_SINGLE_LOOP);
            delay(50);
            mp3.playAudio();
        }
    } else if (!should_active && is_alarm_active) {
        digitalWrite(OUTPUT_PIN, RELAY_OFF);
        
        portENTER_CRITICAL(&configMux);
        is_alarm_active = false;
        portEXIT_CRITICAL(&configMux);
        
        Serial.printf("[ALARM] DEACTIVATED: %02d:%02d\n", sharedHours, sharedMinutes);
        if (mp3_ok) mp3.stopAudio();
    }

    if (is_alarm_active) {
        showLED(manual && !rtc_active ? 0x0000FF : 0x00FF00); 
    } else {
        showLED(0xFF0000); 
    }
}

// ===================================================================================
// WEB HANDLERS (Core 0)
// ===================================================================================
void handleRoot() {
    char str_buffer[128];

    portENTER_CRITICAL(&configMux);
    int  dispH    = sharedHours;
    int  dispM    = sharedMinutes;
    int  dispS    = sharedSeconds;
    int  dispD    = sharedDay;
    int  dispMon  = sharedMonth;
    int  dispY    = sharedYear;
    bool active   = is_alarm_active;
    bool manual   = manual_play;
    int  vol      = alarmConfig.volume;
    int  nperiods = alarmConfig.num_periods;
    Period periods_copy[MAX_PERIODS];
    for (int i = 0; i < MAX_PERIODS; i++) periods_copy[i] = alarmConfig.periods[i];
    portEXIT_CRITICAL(&configMux);

    String html =
        "<!DOCTYPE html><html><head>"
        "<title>GRAVE Controller</title>"
        "<meta charset='UTF-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        "<style>"
        "body{font-family:sans-serif;background:#f0f0f0;max-width:400px;margin:0 auto;padding:10px;}"
        "div{background:#fff;border-radius:5px;padding:20px;margin-bottom:10px;}"
        "h1,h2{color:#333;}p{color:#555;}"
        "form{display:grid;grid-template-columns:1fr 1fr;gap:10px;}"
        "label{font-weight:bold;}"
        "input[type='number']{width:90%;padding:5px;}"
        "input[type='submit']{grid-column:1/-1;padding:10px;background:#007bff;"
        "color:#fff;border:none;border-radius:5px;font-size:1em;cursor:pointer;}"
        "h3{grid-column:1/-1;margin:5px 0;border-bottom:1px solid #ccc;padding-bottom:5px;}"
        "</style></head><body>"
        "<h1>GRAVE Controller</h1>";

    html += "<div><h2>Estado Atual</h2>";
    snprintf(str_buffer, sizeof(str_buffer),
        "<p>Hora RTC: <strong>%02d:%02d:%02d</strong> &nbsp; %02d/%02d/%04d</p>",
        dispH, dispM, dispS, dispD, dispMon, dispY);
    html += str_buffer;
    String st = active ? (manual ? "ON (Manual)" : "ON (Auto)") : "OFF";
    snprintf(str_buffer, sizeof(str_buffer),
        "<p>AMP / MP3: <strong>%s</strong> | Volume: %d</p>",
        st.c_str(), vol);
    html += str_buffer;
    html += "</div>";

    html += "<div><h2>Controle de Volume do MP3</h2>";
    html += "<p>Ajuste o volume (0-30). Atual: <strong>" + String(vol) + "</strong>.</p>";
    html += "<form action='/setvolume' method='POST' style='grid-template-columns:1fr;'>";
    // Slider limit reduced to 30
    html += "<input type='range' name='v' min='0' max='30' value='"
            + String(vol) + "' style='width:95%;margin:10px 0;'>";
    html += "<input type='submit' value='Salvar Volume'>";
    html += "</form></div>";

    html += "<div><h2>Per&iacute;odos de Ativa&ccedil;&atilde;o</h2>";
    if (nperiods == 0) {
        html += "<p style='color:red;'>Nenhum per&iacute;odo ativo.</p>";
    } else {
        html += "<ul>";
        for (int i = 0; i < nperiods; i++) {
            snprintf(str_buffer, sizeof(str_buffer),
                "<li>Per&iacute;odo %d: <strong>%02d:%02d</strong>"
                " &agrave;s <strong>%02d:%02d</strong></li>",
                i + 1,
                periods_copy[i].start_h, periods_copy[i].start_m,
                periods_copy[i].end_h,   periods_copy[i].end_m);
            html += str_buffer;
        }
        html += "</ul>";
    }
    html += "<form action='/set' method='POST'>";
    for (int i = 0; i < MAX_PERIODS; i++) {
        Period p = (i < nperiods) ? periods_copy[i] : Period();
        snprintf(str_buffer, sizeof(str_buffer), "<h3>Per&iacute;odo %d</h3>", i + 1);
        html += str_buffer;
        html += "<label>Hora In&iacute;cio:</label><label>Min. In&iacute;cio:</label>";
        snprintf(str_buffer, sizeof(str_buffer),
            "<input type='number' name='sh%d' min='0' max='23' value='%d'>",
            i, p.start_h);
        html += str_buffer;
        snprintf(str_buffer, sizeof(str_buffer),
            "<input type='number' name='sm%d' min='0' max='59' value='%d'>",
            i, p.start_m);
        html += str_buffer;
        html += "<label>Hora Fim:</label><label>Min. Fim:</label>";
        snprintf(str_buffer, sizeof(str_buffer),
            "<input type='number' name='eh%d' min='0' max='23' value='%d'>",
            i, p.end_h);
        html += str_buffer;
        snprintf(str_buffer, sizeof(str_buffer),
            "<input type='number' name='em%d' min='0' max='59' value='%d'>",
            i, p.end_m);
        html += str_buffer;
    }
    html += "<p style='grid-column:1/-1;font-size:0.85em;'>"
            "* Per&iacute;odos com in&iacute;cio igual ao fim s&atilde;o ignorados.</p>";
    html += "<input type='submit' value='Salvar Per&iacute;odos'>";
    html += "</form></div>";

    html += "<div><h2>Ajustar Hora RTC</h2>";
    html += "<form action='/settime' method='POST'"
            " style='grid-template-columns:1fr 1fr 1fr;'>";
    html += "<h3>Hora</h3><label>H</label><label>M</label><label>S</label>";
    snprintf(str_buffer, sizeof(str_buffer),
        "<input type='number' name='h' min='0' max='23' value='%d'>", dispH);
    html += str_buffer;
    snprintf(str_buffer, sizeof(str_buffer),
        "<input type='number' name='m' min='0' max='59' value='%d'>", dispM);
    html += str_buffer;
    snprintf(str_buffer, sizeof(str_buffer),
        "<input type='number' name='s' min='0' max='59' value='%d'>", dispS);
    html += str_buffer;
    html += "<h3>Data</h3><label>Dia</label><label>M&ecirc;s</label><label>Ano</label>";
    snprintf(str_buffer, sizeof(str_buffer),
        "<input type='number' name='d' min='1' max='31' value='%d'>", dispD);
    html += str_buffer;
    snprintf(str_buffer, sizeof(str_buffer),
        "<input type='number' name='mon' min='1' max='12' value='%d'>", dispMon);
    html += str_buffer;
    snprintf(str_buffer, sizeof(str_buffer),
        "<input type='number' name='y' min='2024' max='2100' value='%d'>", dispY);
    html += str_buffer;
    html += "<input type='submit' value='Definir Hora'>";
    html += "</form></div></body></html>";

    server.send(200, "text/html", html);
}

void handleSet() {
    if (server.method() != HTTP_POST) {
        server.send(405, "text/plain", "Method not allowed"); return;
    }
    AlarmData nc;
    int cnt = 0;
    for (int i = 0; i < MAX_PERIODS; i++) {
        int sh = constrain(server.arg("sh" + String(i)).toInt(), 0, 23);
        int sm = constrain(server.arg("sm" + String(i)).toInt(), 0, 59);
        int eh = constrain(server.arg("eh" + String(i)).toInt(), 0, 23);
        int em = constrain(server.arg("em" + String(i)).toInt(), 0, 59);
        if (sh * 60 + sm == eh * 60 + em) continue; 
        nc.periods[cnt++] = {sh, sm, eh, em};
    }
    nc.num_periods = cnt;

    portENTER_CRITICAL(&configMux);
    nc.volume    = alarmConfig.volume; 
    nc.signature = EEPROM_SIGNATURE;
    alarmConfig  = nc;
    portEXIT_CRITICAL(&configMux);

    saveAlarmConfig();
    server.sendHeader("Location", "/", true);
    server.send(302, "text/plain", "");
}

void handleSetVolume() {
    if (server.method() != HTTP_POST) {
        server.send(405, "text/plain", "Method not allowed"); return;
    }
    int v = constrain(server.arg("v").toInt(), 0, 30); // Max clamped to 30

    portENTER_CRITICAL(&configMux);
    alarmConfig.volume     = v;
    pendingVolumeValue     = (uint8_t)v;
    pendingVolumeFlag      = true;
    portEXIT_CRITICAL(&configMux);

    saveAlarmConfig();
    server.sendHeader("Location", "/", true);
    server.send(302, "text/plain", "");
}

void handleSetTime() {
    if (server.method() != HTTP_POST) {
        server.send(405, "text/plain", "Method not allowed"); return;
    }
    portENTER_CRITICAL(&configMux);
    pendingTime.h   = constrain(server.arg("h").toInt(),   0,    23);
    pendingTime.m   = constrain(server.arg("m").toInt(),   0,    59);
    pendingTime.s   = constrain(server.arg("s").toInt(),   0,    59);
    pendingTime.d   = constrain(server.arg("d").toInt(),   1,    31);
    pendingTime.mon = constrain(server.arg("mon").toInt(), 1,    12);
    pendingTime.y   = constrain(server.arg("y").toInt(),   2024, 2100);
    pendingTimeFlag = true;
    portEXIT_CRITICAL(&configMux);

    server.sendHeader("Location", "/", true);
    server.send(302, "text/plain", "");
}

void handleNotFound() { server.send(404, "text/plain", "404: Not found"); }

// ===================================================================================
// CORE 0 TASK: Web Server
// ===================================================================================
void WebServerTask(void* parameter) {
    WiFi.disconnect(true);
    WiFi.mode(WIFI_AP);
    WiFi.softAPConfig(AP_IP, AP_GATEWAY, AP_SUBNET);
    WiFi.softAP(ap_ssid, ap_password);
    Serial.printf("[WIFI] AP started - SSID: %s  IP: %s\n",
                  ap_ssid, AP_IP.toString().c_str());

    server.on("/",          HTTP_GET,  handleRoot);
    server.on("/set",       HTTP_POST, handleSet);
    server.on("/settime",   HTTP_POST, handleSetTime);
    server.on("/setvolume", HTTP_POST, handleSetVolume);
    server.onNotFound(handleNotFound);
    server.begin();
    Serial.println("[WEB] Server ready at http://192.168.4.1");

    while (true) {
        server.handleClient();
        delay(5); 
    }
}

// ===================================================================================
// SETUP (Core 1)
// ===================================================================================
void setup() {
    Serial.begin(115200);
    delay(500);
    Serial.println("\n========================================");
    Serial.println("  GRAVE Controller v6.9-final");
    Serial.println("========================================");

    AtomS3.begin(true);
    AtomS3.dis.setBrightness(100);
    showLED(0xFFFFFF); 

    if (M5.Rtc.isEnabled()) {
        auto dt = M5.Rtc.getDateTime();
        
        portENTER_CRITICAL(&configMux);
        sharedHours   = dt.time.hours;
        sharedMinutes = dt.time.minutes;
        sharedSeconds = dt.time.seconds;
        sharedDay     = dt.date.date;
        sharedMonth   = dt.date.month;
        sharedYear    = dt.date.year;
        portEXIT_CRITICAL(&configMux);
        
        Serial.printf("[RTC] OK - %02d:%02d:%02d\n", dt.time.hours, dt.time.minutes, dt.time.seconds);
    }

    Serial1.begin(9600, SERIAL_8N1, MP3_RX_PIN, MP3_TX_PIN);

    Serial.print("[MP3] Connecting");
    for (int t = 0; t < 10; t++) {
        showLED(t % 2 == 0 ? 0xFF8000 : 0x000000); 
        bool ok = mp3.begin(&Serial1, MP3_RX_PIN, MP3_TX_PIN);
        if (ok) {
            mp3_ok = true;
            Serial.println(" OK");
            break;
        }
        if (t > 0) Serial.print("."); 
        delay(500);
    }

    pinMode(OUTPUT_PIN, OUTPUT);
    digitalWrite(OUTPUT_PIN, RELAY_OFF); 

    if (!EEPROM.begin(EEPROM_SIZE)) {
        Serial.println("[EEPROM] FATAL: init failed. Halting.");
        while (true);
    }
    loadAlarmConfig();
    
    // Test Block
    Serial.println("[TEST] 15-second hardware test...");
    digitalWrite(OUTPUT_PIN, RELAY_ON); 
    
    if (mp3_ok) {
        mp3.setVolume((uint8_t)alarmConfig.volume);
        delay(50);
        mp3.setPlayMode(AUDIO_PLAYER_MODE_SINGLE_LOOP);
        delay(50);
        mp3.playAudio();
    }
    showLED(0x0000FF); 
    delay(15000);
    
    digitalWrite(OUTPUT_PIN, RELAY_OFF);
    if (mp3_ok) mp3.stopAudio();
    showLED(0x000000);
    Serial.println("[TEST] Complete.");

    xTaskCreatePinnedToCore(
        WebServerTask, "WebTask", 8192, NULL, 1, &webTaskHandle, 0
    );

    previousMillis = millis();
    showLED(0xFF0000); 
}

// ===================================================================================
// LOOP (Core 1 only)
// ===================================================================================
void loop() {
    AtomS3.update();

    unsigned long now = millis();

    if (now - previousMillis >= alarmInterval) {
        previousMillis = now;

        portENTER_CRITICAL(&configMux);
        bool doTime = pendingTimeFlag;
        PendingTime pt = pendingTime;
        if (doTime) pendingTimeFlag = false;
        portEXIT_CRITICAL(&configMux);

        if (doTime) {
            m5::rtc_datetime_t nd;
            nd.time.hours   = pt.h;
            nd.time.minutes = pt.m;
            nd.time.seconds = pt.s;
            nd.date.date    = pt.d;
            nd.date.month   = pt.mon;
            nd.date.year    = pt.y;
            nd.date.weekDay = 1;
            M5.Rtc.setDateTime(nd);
            Serial.printf("[RTC] Time set: %02d:%02d:%02d\n", pt.h, pt.m, pt.s);
        }

        portENTER_CRITICAL(&configMux);
        bool doVol = pendingVolumeFlag;
        uint8_t vol = pendingVolumeValue;
        if (doVol) pendingVolumeFlag = false;
        portEXIT_CRITICAL(&configMux);

        if (doVol && mp3_ok) {
            mp3.setVolume(vol);
            Serial.printf("[MP3] Volume set: %d\n", vol);
        }

        auto dt = M5.Rtc.getDateTime();

        portENTER_CRITICAL(&configMux);
        sharedHours   = dt.time.hours;
        sharedMinutes = dt.time.minutes;
        sharedSeconds = dt.time.seconds;
        sharedDay     = dt.date.date;
        sharedMonth   = dt.date.month;
        sharedYear    = dt.date.year;
        portEXIT_CRITICAL(&configMux);

        checkAlarmState();
    }

    if (AtomS3.BtnA.wasPressed()) {
        portENTER_CRITICAL(&configMux);
        manual_play = !manual_play;
        bool mp = manual_play;
        portEXIT_CRITICAL(&configMux);
        Serial.printf("[BUTTON] manual_play -> %s\n", mp ? "ON" : "OFF");
        checkAlarmState();
    }

    delay(1);
}
